### ISSUE TITLE
Unable to comment within playback

### ISSUE THREAD

**Issue by reZach** [markm208/storyteller#6]
v. 0.0.8

Steps to reproduce:
1. Create a new directory
2. Create an index.html file
3. Start tracking this directory as a Storyteller project
4. Begin editing the index.html file
5. Save index.html
6. From the VSCode command palette, click Storyteller: Comment
7. Notice a new tab opens up in an browser with the playback
8. Type in text and click Add Comment
9. There is an error in the browser that reads: **SyntaxError: The string did not match the expected pattern.**

**Comment by reZach** [comment]
I created the new directory in the file explorer.

**Comment by markm208** [comment]
Is what you did any different from this video? If so, which part?

![zachtest](https://user-images.githubusercontent.com/934916/44071148-1e9339a2-9f4d-11e8-957e-d17293256597.gif)

**Comment by reZach** [comment]
Ah, I see now. When I was adding a developer to the story, I just typed in my email and not 

`FirstName LastName Email`.

I assume because I only added an email, your pattern matching was unable to pull what it needs and that is why the Add Comment button bugs out.

**Comment by markm208** [comment]
Hmmm... even with just an email it worked on my machine. Can you try with your full name and email and see if that makes a difference?

**Comment by reZach** [comment]
It looks like everything is working as expected in Chrome, but I am unable to add a comment in my Safari browser. Upon a bit of searching it appears you just need to update your selector in this statement to include the closing `]` bracket. All other browsers handle this gracefully _except_ Safari.

Change
`document.querySelectorAll("[class*=beginSelectedCode-")`

to
`document.querySelectorAll("[class*=beginSelectedCode-]")`

**Comment by reZach** [comment]
Created a pull request with these changes, see below.

https://github.com/markm208/storyteller/pull/7

**Comment by reZach** [comment]
Comments are now added in safari, thanks for merging in the pull request!
